dir:
  input: samples/
  output: null  # If not specified, outputs files to same dir as input.

file_ext:
  rgb: .rgb.png  # The files you want to apply distortion to
  info: .info.json  # Contains camera intrinsics
  depth: .depth.tif

# Config specifically for the 3D landmarks
landmarks_3d:
  render_id: -1  # Process this render id. If -1, will process all images
  visualize: false # Whether to show the result in a window. true

workers: 0  # How many processes to use to convert files. 0 for all cores in machine.

# Hydra specific params.
hydra:
    output_subdir: null  # Disable saving of config files.
    run:
        dir: .  # Set working dir to current directory

defaults:
    # Disable log files
    - hydra/job_logging: default
    - hydra/hydra_logging: disabled
